auth_controllers:
    resource: ../src/Auth/Controller/
    type: attribute

welcome_controllers:
    resource: ../src/Welcome/Controller/
    type: attribute

tasks_controllers:
    resource: ../src/Tasks/Controller/
    type: attribute
